import { BalanceDirection, PaymentMethod } from '../src/schemas/schema.types';

/** Product definitions — realistic Pakistani pharmacy inventory */
export const SEED_PRODUCTS = [
  {
    key: 'panadol-500',
    name: 'Panadol 500mg',
    shortDescription: 'Pain relief and fever reducer',
    descriptionUrdu: 'درد اور بخار کی دوا',
    formulation: 'Paracetamol',
    packType: 'Tablet',
    size: 10,
    unitPrice: 85,
    purchasePrice: 60,
    gstPercent: 0,
    quantityInStock: 480,
    lowStockThreshold: 50,
    batchNo: 'PN-2026-A14',
    expiry: '2027-06',
    mfg: '2025-08',
  },
  {
    key: 'brufen-400',
    name: 'Brufen 400mg',
    shortDescription: 'Anti-inflammatory painkiller',
    descriptionUrdu: 'سوجن اور درد کی دوا',
    formulation: 'Ibuprofen',
    packType: 'Tablet',
    size: 20,
    unitPrice: 120,
    purchasePrice: 85,
    gstPercent: 0,
    quantityInStock: 320,
    lowStockThreshold: 40,
    batchNo: 'BR-2026-K09',
    expiry: '2027-03',
    mfg: '2025-05',
  },
  {
    key: 'augmentin-625',
    name: 'Augmentin 625mg',
    shortDescription: 'Broad-spectrum antibiotic',
    descriptionUrdu: 'اینٹی بائیوٹک',
    formulation: 'Amoxicillin + Clavulanic Acid',
    packType: 'Tablet',
    size: 14,
    unitPrice: 850,
    purchasePrice: 620,
    gstPercent: 0,
    quantityInStock: 95,
    lowStockThreshold: 15,
    batchNo: 'AG-2026-M22',
    expiry: '2026-12',
    mfg: '2025-02',
  },
  {
    key: 'zithromax-250',
    name: 'Zithromax 250mg',
    shortDescription: 'Macrolide antibiotic',
    descriptionUrdu: 'زکام اور انفیکشن کی دوا',
    formulation: 'Azithromycin',
    packType: 'Capsule',
    size: 6,
    unitPrice: 420,
    purchasePrice: 300,
    gstPercent: 0,
    quantityInStock: 140,
    lowStockThreshold: 20,
    batchNo: 'ZT-2026-B07',
    expiry: '2027-01',
    mfg: '2025-03',
  },
  {
    key: 'volini-gel',
    name: 'Volini Gel 30g',
    shortDescription: 'Topical pain relief gel',
    descriptionUrdu: 'جسمانی درد کی مرہم',
    formulation: 'Diclofenac Diethylamine',
    packType: 'Tube',
    size: 1,
    unitPrice: 280,
    purchasePrice: 200,
    gstPercent: 0,
    quantityInStock: 65,
    lowStockThreshold: 10,
    batchNo: 'VG-2026-T11',
    expiry: '2027-08',
    mfg: '2025-10',
  },
  {
    key: 'disprin',
    name: 'Disprin 300mg',
    shortDescription: 'Soluble aspirin tablets',
    descriptionUrdu: 'سر درد کی فوری دوا',
    formulation: 'Aspirin',
    packType: 'Tablet',
    size: 100,
    unitPrice: 45,
    purchasePrice: 30,
    gstPercent: 0,
    quantityInStock: 8,
    lowStockThreshold: 15,
    batchNo: 'DS-2025-Z03',
    expiry: '2026-09',
    mfg: '2024-11',
  },
  {
    key: 'nexum-40',
    name: 'Nexum 40mg',
    shortDescription: 'Acid reflux and GERD treatment',
    descriptionUrdu: 'معدے کی تیزابیت',
    formulation: 'Esomeprazole',
    packType: 'Capsule',
    size: 14,
    unitPrice: 650,
    purchasePrice: 470,
    gstPercent: 0,
    quantityInStock: 110,
    lowStockThreshold: 20,
    batchNo: 'NX-2026-E18',
    expiry: '2027-04',
    mfg: '2025-06',
  },
  {
    key: 'flagyl-400',
    name: 'Flagyl 400mg',
    shortDescription: 'Antiprotozoal and antibacterial',
    descriptionUrdu: 'پیٹ کے انفیکشن کی دوا',
    formulation: 'Metronidazole',
    packType: 'Tablet',
    size: 21,
    unitPrice: 95,
    purchasePrice: 65,
    gstPercent: 0,
    quantityInStock: 200,
    lowStockThreshold: 30,
    batchNo: 'FL-2026-H05',
    expiry: '2027-02',
    mfg: '2025-04',
  },
  {
    key: 'rinza',
    name: 'Rinza',
    shortDescription: 'Cold and flu combination therapy',
    descriptionUrdu: 'نزلہ زکام کی دوا',
    formulation: 'Paracetamol + Phenylephrine + Caffeine',
    packType: 'Tablet',
    size: 10,
    unitPrice: 110,
    purchasePrice: 78,
    gstPercent: 0,
    quantityInStock: 175,
    lowStockThreshold: 25,
    batchNo: 'RZ-2026-C12',
    expiry: '2027-05',
    mfg: '2025-07',
  },
  {
    key: 'calpol-syrup',
    name: 'Calpol 120mg/5ml Syrup',
    shortDescription: 'Paediatric fever and pain syrup',
    descriptionUrdu: 'بچوں کے بخار کی شربت',
    formulation: 'Paracetamol',
    packType: 'Syrup',
    size: 60,
    unitPrice: 165,
    purchasePrice: 115,
    gstPercent: 0,
    quantityInStock: 90,
    lowStockThreshold: 15,
    batchNo: 'CP-2026-S08',
    expiry: '2026-11',
    mfg: '2025-01',
  },
  {
    key: 'insulatard',
    name: 'Insulatard FlexPen 100IU/ml',
    shortDescription: 'Intermediate-acting human insulin',
    descriptionUrdu: 'ذیابیطس کی انسولین',
    formulation: 'Insulin Human (NPH)',
    packType: 'FlexPen',
    size: 1,
    unitPrice: 2850,
    purchasePrice: 2350,
    gstPercent: 0,
    quantityInStock: 24,
    lowStockThreshold: 5,
    batchNo: 'IN-2026-D01',
    expiry: '2026-08',
    mfg: '2025-02',
  },
  {
    key: 'ors-sachet',
    name: 'Hydralyte ORS Sachet',
    shortDescription: 'Oral rehydration salts',
    descriptionUrdu: 'پانی کی کمی دور کرنے والا پاؤڈر',
    formulation: 'Oral Rehydration Salts',
    packType: 'Sachet',
    size: 1,
    unitPrice: 35,
    purchasePrice: 22,
    gstPercent: 0,
    quantityInStock: 500,
    lowStockThreshold: 100,
    batchNo: 'OR-2026-P30',
    expiry: '2028-01',
    mfg: '2026-01',
  },
] as const;

/** Wholesale customers — pharmacies, clinics, and hospitals across Pakistan */
export const SEED_CUSTOMERS = [
  {
    key: 'al-shifa-karachi',
    firstName: 'Al-Shifa',
    lastName: 'Medical Store',
    phoneNumber: '03001234567',
    email: 'orders@alshifapharmacy.pk',
    streetAddress: 'Shop 12, Tariq Road, PECHS',
    city: 'Karachi',
    state: 'Sindh',
  },
  {
    key: 'city-pharmacy-lahore',
    firstName: 'City',
    lastName: 'Pharmacy',
    phoneNumber: '03211234567',
    email: 'purchase@citypharmacy.com.pk',
    streetAddress: '45 Mall Road, Gulberg II',
    city: 'Lahore',
    state: 'Punjab',
    balanceAdjustment: {
      amount: 12500,
      direction: BalanceDirection.CUSTOMER_OWES,
      note: 'Carried forward balance from December 2025 statement',
    },
  },
  {
    key: 'fatima-clinic',
    firstName: 'Dr. Fatima',
    lastName: 'Siddiqui Clinic',
    phoneNumber: '03331234567',
    email: 'clinic@drfatimasiddiqui.pk',
    streetAddress: 'House 8, Street 14, F-8 Markaz',
    city: 'Islamabad',
    state: 'ICT',
  },
  {
    key: 'rehman-hospital',
    firstName: 'Rehman',
    lastName: 'General Hospital',
    phoneNumber: '03451234567',
    email: 'pharmacy@rehmangh.org',
    streetAddress: 'Murree Road, Satellite Town',
    city: 'Rawalpindi',
    state: 'Punjab',
  },
  {
    key: 'hussain-medico',
    firstName: 'Hussain',
    lastName: 'Medico',
    phoneNumber: '03111234567',
    email: 'hussainmedico@gmail.com',
    streetAddress: 'Katchery Bazaar, Clock Tower',
    city: 'Faisalabad',
    state: 'Punjab',
  },
  {
    key: 'green-valley',
    firstName: 'Green Valley',
    lastName: 'Pharmacy',
    phoneNumber: '03051234567',
    email: 'info@greenvalleypharmacy.pk',
    streetAddress: 'Bosan Road, Gulgasht Colony',
    city: 'Multan',
    state: 'Punjab',
    balanceAdjustment: {
      amount: 3200,
      direction: BalanceDirection.WE_OWE_CUSTOMER,
      note: 'Credit note for damaged Augmentin batch returned in January',
    },
  },
  {
    key: 'al-noor-peshawar',
    firstName: 'Al-Noor',
    lastName: 'Homeo & Pharmacy',
    phoneNumber: '03401234567',
    email: 'alnoor.peshawar@outlook.com',
    streetAddress: 'University Road, University Town',
    city: 'Peshawar',
    state: 'KPK',
  },
  {
    key: 'zainab-dispensary',
    firstName: 'Zainab',
    lastName: 'Welfare Dispensary',
    phoneNumber: '03331234568',
    email: 'zainabwelfare@gmail.com',
    streetAddress: 'Jinnah Town, Sariab Road',
    city: 'Quetta',
    state: 'Balochistan',
  },
] as const;

export type SeedOrderSpec = {
  key: string;
  customerKey: string;
  note: string;
  items: { productKey: string; quantity: number; discountPercentage?: number }[];
  confirm?: boolean;
  cancel?: boolean;
  returnAfterConfirm?: boolean;
  payments?: {
    amount: number;
    method: PaymentMethod;
    note?: string;
    /** Pay this fraction of order total instead of fixed amount */
    fractionOfTotal?: number;
  }[];
};

export const SEED_ORDERS: SeedOrderSpec[] = [
  {
    key: 'ord-al-shifa-weekly',
    customerKey: 'al-shifa-karachi',
    note: 'Weekly restock — fast-moving OTC items',
    items: [
      { productKey: 'panadol-500', quantity: 40 },
      { productKey: 'brufen-400', quantity: 25 },
      { productKey: 'disprin', quantity: 5, discountPercentage: 5 },
    ],
    confirm: true,
    payments: [{ amount: 0, method: PaymentMethod.CASH, note: 'Paid in full at delivery', fractionOfTotal: 1 }],
  },
  {
    key: 'ord-al-shifa-pending',
    customerKey: 'al-shifa-karachi',
    note: 'Standing order — awaiting confirmation after stock check',
    items: [
      { productKey: 'rinza', quantity: 30 },
      { productKey: 'calpol-syrup', quantity: 15 },
    ],
  },
  {
    key: 'ord-city-pharmacy-antibiotics',
    customerKey: 'city-pharmacy-lahore',
    note: 'Antibiotic bulk order for flu season',
    items: [
      { productKey: 'augmentin-625', quantity: 8, discountPercentage: 3 },
      { productKey: 'zithromax-250', quantity: 12 },
      { productKey: 'flagyl-400', quantity: 20 },
    ],
    confirm: true,
    payments: [
      {
        amount: 0,
        method: PaymentMethod.JAZZCASH,
        note: 'Partial payment — balance due in 15 days',
        fractionOfTotal: 0.6,
      },
    ],
  },
  {
    key: 'ord-fatima-clinic-gi',
    customerKey: 'fatima-clinic',
    note: 'Monthly GI medicines for outpatient clinic',
    items: [
      { productKey: 'nexum-40', quantity: 6 },
      { productKey: 'flagyl-400', quantity: 10 },
    ],
    confirm: true,
  },
  {
    key: 'ord-rehman-hospital-insulin',
    customerKey: 'rehman-hospital',
    note: 'Hospital pharmacy — insulin and ORS restock',
    items: [
      { productKey: 'insulatard', quantity: 10, discountPercentage: 2 },
      { productKey: 'ors-sachet', quantity: 100 },
      { productKey: 'calpol-syrup', quantity: 20 },
    ],
    confirm: true,
    payments: [
      {
        amount: 0,
        method: PaymentMethod.BANK_TRANSFER,
        note: 'Hospital accounts — Ref HOSP-2026-0142',
        fractionOfTotal: 1,
      },
    ],
  },
  {
    key: 'ord-hussain-medico-small',
    customerKey: 'hussain-medico',
    note: 'Counter sale replenishment',
    items: [
      { productKey: 'volini-gel', quantity: 12 },
      { productKey: 'panadol-500', quantity: 20 },
    ],
    confirm: true,
    payments: [
      {
        amount: 0,
        method: PaymentMethod.EASYPAISA,
        note: 'Easypaisa merchant payment',
        fractionOfTotal: 1,
      },
    ],
  },
  {
    key: 'ord-hussain-cancelled',
    customerKey: 'hussain-medico',
    note: 'Cancelled — customer switched to different brand',
    items: [{ productKey: 'augmentin-625', quantity: 5 }],
    cancel: true,
  },
  {
    key: 'ord-green-valley-return',
    customerKey: 'green-valley',
    note: 'Order fulfilled then partially returned (near-expiry Disprin)',
    items: [
      { productKey: 'disprin', quantity: 3 },
      { productKey: 'brufen-400', quantity: 10 },
    ],
    confirm: true,
    returnAfterConfirm: true,
    payments: [
      {
        amount: 0,
        method: PaymentMethod.CASH,
        note: 'Paid before return was processed',
        fractionOfTotal: 1,
      },
    ],
  },
  {
    key: 'ord-al-noor-mixed',
    customerKey: 'al-noor-peshawar',
    note: 'Mixed order — homeopathic counter + allopathy',
    items: [
      { productKey: 'rinza', quantity: 25 },
      { productKey: 'panadol-500', quantity: 50 },
      { productKey: 'ors-sachet', quantity: 80, discountPercentage: 10 },
    ],
    confirm: true,
    payments: [
      {
        amount: 0,
        method: PaymentMethod.CASH,
        note: 'Partial cash on delivery',
        fractionOfTotal: 0.5,
      },
    ],
  },
  {
    key: 'ord-zainab-welfare',
    customerKey: 'zainab-dispensary',
    note: 'NGO subsidized order — essential medicines',
    items: [
      { productKey: 'panadol-500', quantity: 30 },
      { productKey: 'calpol-syrup', quantity: 25 },
      { productKey: 'ors-sachet', quantity: 150, discountPercentage: 15 },
    ],
    confirm: true,
    payments: [
      {
        amount: 0,
        method: PaymentMethod.BANK_TRANSFER,
        note: 'NGO grant disbursement — Ref ZW-2026-03',
        fractionOfTotal: 0.75,
      },
    ],
  },
];

/** Standalone payments not tied to a specific order */
export const SEED_STANDALONE_PAYMENTS = [
  {
    customerKey: 'fatima-clinic',
    amount: 5000,
    method: PaymentMethod.BANK_TRANSFER,
    note: 'Advance payment against running account',
  },
  {
    customerKey: 'city-pharmacy-lahore',
    amount: 8000,
    method: PaymentMethod.CASH,
    note: 'On-account settlement — old invoice clearance',
  },
] as const;
